branches:
  - name: main
    prerelease: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - publishCmd: |
        git checkout -b release/${nextRelease.version}
        git push origin release/${nextRelease.version}
  - - "@semantic-release/git"
    - message: 'chore(release): ${nextRelease.version}'
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - publishCmd: |
        echo "${nextRelease.notes}" > /tmp/release-notes.md
