version: 2.1

master_only: &main_only
  filters:
    branches:
      only: main

orbs:
  node: circleci/node@5.1.0

jobs:
  deploy:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - run:
          name: Deploy to Staging
          command: |
            echo "Deploying to staging"
  release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Create release branch
          command: |
            npx semantic-release --dry-run --no-ci
            test -e .VERSION || git checkout -b release/$(cat .VERSION)
      - run: npx semantic-release

workflows:
  stack:
    jobs:
      - deploy:
          name: deploy_staging
          <<: *main_only
      - hold_release:
          type: approval
          requires:
            - deploy_staging
          <<: *main_only
      - release:
          requires:
            - hold_release
          <<: *main_only
